# Generated by Django 5.2.2 on 2025-06-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinvestment',
            old_name='currrent_value',
            new_name='current_value',
        ),
    ]
