services:
  redis:
    image: redis:latest
    container_name: cont-redis
    restart: always
    environment:
      TZ: "Asia/Jakarta"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
