[project]
name = "investment-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "djangorestframework-simplejwt>=5.5.0",
]
